A FAZER NO SITE EMEMORA:

- COMPONENTE PARA BOTÃO DE VOLTAR E USAR NO TOPO DE QUIZ, FLASHCARD, ETC.
- FUNCIONALIDADE DE LIKES (E DESLIKES?)

- CHECKBOX 'LISTAS FAVORITADAS' NA HOME
- AO JOGAR QUIZ: PÁGINA DE CONFIGURAÇÃO PARA DETERMINAR QUANTIDADE DE TERMOS A SEREM USADOS (MINIMO 4 E MÁXIMO == QTD_TERMOS_LISTA)
- USUARIOS NAO AUTENTICADOS NAO PODEM CRIAR LISTAS

- LIDAR COM USUÁRIO DELETANDO TERMO OU LISTA DE TERMOS QUE CONTENHAM IMAGEM. DEVO EXCLUIR IMAGEM NO CLOUDINARY, OU NÃO. (ABORDAGEM DA NÃO REDUNDÂNCIA: SE 2 OU MAIS USUÁRIOS TIVEREM A MESMA IMAGEM EM SUAS LISTAS NÃO EXCLUIR IMAGEM. NECESSÁRIO CRIAR SCHEMA PARA IMAGEM, TALVEZ?)

- USUARIOS NAO AUTENTICADOS PODEM JOGAR QUIZ, FLASHCARD e LISTA DE TERMOS, MAS STATUS DE TERMOS NAO MUDA
- BOTÃO DE EDITAR LISTA VISIVEL SOMENTE AO AUTOR
- MOSTRAR AUTOR E NUMERO DE TERMOS NO CARD DA LISTA
- EM REGISTER TROCAR ALERT 'VERIFIQUE SEU EMAIL' POR REDIRECIONAMENTO A UMA ROTA QUE DIRECIONA AO EMAIL, OU ALGO SIMILAR COMO MOSTRAR EMAIL ONDE FOI ENVIADO O LINK DE VERIFICAÇÃO
- FUNCIONALIDADE DE ADICIONAR TERMOS NA LISTA POR ALGUM FORMATO COMO .JSON OU SIMILAR (EX: CACHORRO=INU;GATO=NEKO)
- FUNCIONALIDADE DE FAVORITAR (E ADICIONAR NA ROTA ROOT OU /USERS/[UID] ??)
- CONSERTAR HANDLE LOGIN EMAIL NA ROTA DE LOGIN

- FUNCIONALIDADE DE COPIAR LISTA DOS OUTROS (COMO TIRAR UMA SCREENSHOT)
- LIMITE DE 250 TERMOS POR LISTA E OUTRAS RESTRIÇÕES NA LISTA (E TERMO, E USUÁRIO)
- MELHORAR ESTILIZAÇÃO DE TODO O SITE
- FAZER LOGO DO SITE COM GPTs

- BUG: CLICAR DUAS VEZES EM CRIAR LISTA EM 'NOVA LISTA' CRIA DUAS LISTAS (2 POSTS)
- BUG: USUÁRIO CONSEGUE FAZER UPLOAD FOTO NO CLOUDINARY E NÃO SALVAR LISTA
- ADICIONAR FAVICON DO SITE