A FAZER NO SITE EMEMORA:

-modularizar /lists/[id]/edit criando componente como editTerm
- FUNCIONALIDADE DE ADICIONAR TERMOS NA LISTA POR ALGUM FORMATO COMO .JSON OU SIMILAR (EX: CACHORRO=INU;GATO=NEKO)
-em /api/upload: no upload para cloudinary nomear a imagem com id do usuario para eu saber quem enviou
-flashcard revisão: status dos icones não está atualizado (cor original?)

- EM lists/[listId] ao resetar progresso, paginação não ocorre
-mudar cor de like/dislike para usuário saber se ele já votou
- APÓS ADICIONAR PAGINACAO EM /LISTS/[LIST_ID] OCORRE BUG NO SELECT-OPTION: ORDENAR POR e na PROGRESS_BAR

-em lists/[id]/edit: ao adicionar imagem, novo campo de termo aparece (BUG) e fica aparecendo 'Lista salva' o que é irritante
- FUNCIONALIDADE DE FAVORITAR (E ADICIONAR NA ROTA ROOT OU /USERS/[UID] ??)
- CONSERTAR HANDLE LOGIN EMAIL NA ROTA DE LOGIN

-BUG: USUÁRIO CONSEGUE TER NOME NULO. CONSEGUE TER NOME IGUAL A DE OUTRO USUARIO
- FUNCIONALIDADE DE COPIAR LISTA DOS OUTROS (COMO TIRAR UMA SCREENSHOT)
- LIMITE DE 300 TERMOS POR LISTA E OUTRAS RESTRIÇÕES NA LISTA (E TERMO, E USUÁRIO) e limitar 20 LISTAS POR USUÁRIO

-foto de perfil não está redonda (width = height)
- MELHORAR ESTILIZAÇÃO DE TODO O SITE
- FAZER LOGO DO SITE COM GPTs

-tela de carregamento em GameSettings

- LIDAR COM USUÁRIO DELETANDO TERMO OU LISTA DE TERMOS QUE CONTENHAM IMAGEM. DEVO EXCLUIR IMAGEM NO CLOUDINARY, OU NÃO. (ABORDAGEM DA NÃO REDUNDÂNCIA: SE 2 OU MAIS USUÁRIOS TIVEREM A MESMA IMAGEM EM SUAS LISTAS NÃO EXCLUIR IMAGEM. NECESSÁRIO CRIAR SCHEMA PARA IMAGEM, TALVEZ?)

- BUG: CLICAR DUAS VEZES EM CRIAR LISTA EM 'NOVA LISTA' CRIA DUAS LISTAS (2 POSTS)
- BUG: USUÁRIO CONSEGUE FAZER UPLOAD FOTO NO CLOUDINARY E NÃO SALVAR LISTA
- ADICIONAR FAVICON DO SITE